
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Realm-ObjC' do
  pod 'Realm', '~> 3.10.0'

end

target 'Realm-ObjCTests' do
    pod 'Realm', '~> 3.10.0'
    
end
